services:
  postgres:
    container_name: clonathon-postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: clonathon
      POSTGRES_USER: nextjsuser
      POSTGRES_PASSWORD: nextjspassword
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped

  redis:
    container_name: clonathon-redis
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    restart: unless-stopped

volumes:
  postgres:
  redis:
